//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deneme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class address
    {
        public address()
        {
            this.author = new HashSet<author>();
            this.employee = new HashSet<employee>();
            this.library = new HashSet<library>();
            this.member = new HashSet<member>();
            this.publishingHouse = new HashSet<publishingHouse>();
        }
    
        public int aId { get; set; }
        public string doorNumber { get; set; }
        public string street { get; set; }
        public string quarter { get; set; }
        public string district { get; set; }
        public string country { get; set; }
        public string postCode { get; set; }
    
        public virtual ICollection<author> author { get; set; }
        public virtual ICollection<employee> employee { get; set; }
        public virtual ICollection<library> library { get; set; }
        public virtual ICollection<member> member { get; set; }
        public virtual ICollection<publishingHouse> publishingHouse { get; set; }
    }
}
