//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deneme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class book
    {
        public book()
        {
            this.bookLocation = new HashSet<bookLocation>();
            this.trustGet = new HashSet<trustGet>();
            this.category = new HashSet<category>();
            this.author = new HashSet<author>();
        }
    
        public int barcodeNo { get; set; }
        public string isbn { get; set; }
        public string name { get; set; }
        public string numberInformation { get; set; }
        public string pageInformation { get; set; }
        public Nullable<int> libraryNo { get; set; }
        public Nullable<int> publishingHouseNo { get; set; }
    
        public virtual library library { get; set; }
        public virtual publishingHouse publishingHouse { get; set; }
        public virtual ICollection<bookLocation> bookLocation { get; set; }
        public virtual ICollection<trustGet> trustGet { get; set; }
        public virtual ICollection<category> category { get; set; }
        public virtual ICollection<author> author { get; set; }
    }
}
