//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deneme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public int tc { get; set; }
        public int employeNo { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string job { get; set; }
        public string jobToBeginDate { get; set; }
        public string sex { get; set; }
        public Nullable<int> addresNo { get; set; }
        public Nullable<int> kuNo { get; set; }
    
        public virtual address address { get; set; }
        public virtual library library { get; set; }
    }
}
