//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deneme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class library
    {
        public library()
        {
            this.book = new HashSet<book>();
            this.employee = new HashSet<employee>();
            this.register = new HashSet<register>();
        }
    
        public int kuId { get; set; }
        public string name { get; set; }
        public string constructionDate { get; set; }
        public string workTime { get; set; }
        public Nullable<int> addresNo { get; set; }
    
        public virtual address address { get; set; }
        public virtual ICollection<book> book { get; set; }
        public virtual ICollection<employee> employee { get; set; }
        public virtual ICollection<register> register { get; set; }
    }
}
