//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deneme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class member
    {
        public member()
        {
            this.register = new HashSet<register>();
            this.trustGet = new HashSet<trustGet>();
        }
    
        public int memberNo { get; set; }
        public string tc { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string job { get; set; }
        public string telephoneNumber { get; set; }
        public string mailAddress { get; set; }
        public string sex { get; set; }
        public Nullable<int> addressNo { get; set; }
    
        public virtual address address { get; set; }
        public virtual ICollection<register> register { get; set; }
        public virtual ICollection<trustGet> trustGet { get; set; }
    }
}
