//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deneme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class publishingHouse
    {
        public publishingHouse()
        {
            this.book = new HashSet<book>();
        }
    
        public int pId { get; set; }
        public string name { get; set; }
        public Nullable<int> addressNo { get; set; }
    
        public virtual address address { get; set; }
        public virtual ICollection<book> book { get; set; }
    }
}
