//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deneme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trustGet
    {
        public int memberNo { get; set; }
        public int barcodeNo { get; set; }
        public string comment { get; set; }
        public string getDate { get; set; }
        public string returnDate { get; set; }
        public string dept { get; set; }
        public int trustId { get; set; }
    
        public virtual book book { get; set; }
        public virtual member member { get; set; }
    }
}
